name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  REPO_IMAGE:   "mulan04/aqua-runtime-tester"

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build docker image
        run: |
            echo ${{ env.REPO_IMAGE.TAG }}
            # docker build -t ${{ env.REPO_IMAGE.TAG }}:latest .
      
      # - name: Push docker image
        # run: |
            # docker push ${{ env.REPO_IMAGE.TAG }}:latest
          