name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  TAG:          $(date +"%d%m%y%H%M")
  REPO_IMAGE:   "mulan04/aqua-runtime-tester"

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build docker image
        run: |
            docker build -t ${{ REPO_IMAGE.TAG }}:${{ env.TAG }} .
            docker tag ${{ REPO_IMAGE.TAG }}:${{ env.TAG }} ${{ REPO_IMAGE.TAG }}:latest
      
      - name: Push docker image
        run: |
            docker push ${{ REPO_IMAGE.TAG }}:${{ env.TAG }}
            docker push ${{ REPO_IMAGE.TAG }}:latest
          