name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build docker image
        run: sudo docker build -t mulan04/aqua-runtime-tester:${{ github.sha }} .
      
      - name: Build docker image
        run: sudo docker push mulan04/aqua-runtime-tester:${{ github.sha }} .   
          